name: report
on:
  schedule:
    - cron: '23 3,9,15,21 * * *'
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          sudo apt-get install -y tesseract-ocr
          pip install -r requirements.txt
      - name: Report
        env:
          STUID: ${{ secrets.Stuid }}
          PASSWORD: ${{ secrets.Password }}
          EMER_PERSON: ${{ secrets.Emer_person }}
          EMER_RELA: ${{ secrets.Emer_rela }}
          EMER_PHONE: ${{ secrets.Emer_phone }}
          DORM: ${{ secrets.Dorm }}
          DORM_ROOM: ${{ secrets.Dorm_room }}
        run: |
          python report.py data_atschool.json "$STUID" "$PASSWORD" "$EMER_PERSON" "$EMER_RELA" "$EMER_PHONE" "$DORM" "$DORM_ROOM"
